# Generated by Django 4.0 on 2022-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_rename_image_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='predicted',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
