# Generated by Django 4.0 on 2022-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_predicts_remove_images_predicted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Predicts',
        ),
        migrations.AddField(
            model_name='images',
            name='predict',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
