# Generated by Django 4.0 on 2022-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_delete_predicts_images_predict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='predict',
        ),
    ]
